from .xresnet import XResNet
from .xresnet import XResNet18
from .xresnet import XResNet34
from .xresnet import XResNet50
from .xresnet import XResNet101
from .xresnet import XResNet152
from .xresnet import XResNet20
from .xresnet import XResNet32
from .xresnet import XResNet44
from .xresnet import XResNet56
